<a href="https://colab.research.google.com/github/janiosl/C/blob/master/Exercicios/APA/apa_final_featSelect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **CEFET-RJ**

**Programa de Pós-Gradução em Ciência da Computação - PPCIC**

**Mestrado em Ciência da Computação**

**Disciplina: Análise e Projeto de Algoritmos - 2021/2**

* **Trabalho Final**
* **Prof.: Diego Nunes Brandão**
* **Aluno: Cristiane Géa e Janio de Souza Lima**

---

Uma versão online para facilitar a leitura desse notebook foi disponibilizada em: https://github.com/janiosl/C/blob/master/Exercicios/APA/apa_lista03.ipynb

## Preparação do ambiente e carga dos dados

In [98]:
from sklearn.tree import DecisionTreeClassifier

In [99]:
#Bibliotecas
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [100]:
#SEGUNDA OPÇÃO
#Carga do conjunto de dados a partir do GitHub do PythonDS
arquivo = 'https://raw.githubusercontent.com/janiosl/python.ds/master/data/mpg.csv'

In [101]:
dtree = DecisionTreeClassifier()

In [102]:
#Carga e visualização das primeiras observações do conjunto de dados
carros = pd.read_csv(arquivo)
carros.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

## Seção 1: Cálculo da matriz de correlação

In [103]:
#Matriz de correlação de todas as características numéricas
carros.corr()

displ      year       cyl       cty       hwy
displ  1.000000  0.147843  0.930227 -0.798524 -0.766020
year   0.147843  1.000000  0.122245 -0.037232  0.002158
cyl    0.930227  0.122245  1.000000 -0.805771 -0.761912
cty   -0.798524 -0.037232 -0.805771  1.000000  0.955916
hwy   -0.766020  0.002158 -0.761912  0.955916  1.000000

In [104]:
Y = carros.hwy
X = carros.displ

In [105]:
X = np.array(carros.displ)

In [106]:
Y = np.array(carros.hwy)

In [107]:
def raiz(numero):
  """
  Função calcula a raiz quadrada de um número
  """
  prec = 0.001
  b = numero;
  a = 1

  while (b-a) >= prec:
    b = (a+b)/2
    a = numero/b

  return b

In [108]:
def correlacao(X, Y):
  """
  Função calcula o coeficiente de correlação de Pearson entre duas variáveis
  X, Y: Variáveis a serem analisadas
  """
  n = X.shape[0]
  rXY = ((sum(X*Y))-(((sum(X))*(sum(Y)))/(n))) / (raiz(((sum(X ** 2))-((sum(X)**2)/n))*((sum(Y ** 2))-((sum(Y) ** 2)/n))))
  return rXY

In [109]:
correlacao(X, Y)

-0.766020003261723

In [110]:
def matrizCorr(dados):
  """
  Função calcula a matriz de correlação de um conjunto de dados
  OBS.: Deve ser passado um data frame apenas com colunas numéricas
  """
  mc = []
  m = dados.shape[1] #Quantidade de colunas
  n = dados.shape[0]

  for k in range(0, m):
    X = np.array(dados.iloc[:, [k]], ndmin=1)
    for i in range(0, m):
      Y = np.array(dados.iloc[:, [i]], ndmin=1)
      cr = correlacao(X,Y)
      mc.append(cr)

  mc = np.array(mc).reshape(m,m)
  #print(mc)
  return mc

In [111]:
def matrizCorr_(dados):
  """
  Função cálcula matriz de correlação de um conjunto de dados
  Esta versão da função usa métodos embutidos para agilizar
  o tratamento de conjuntos de dados grandes
  """
  mc = []
  m = dados.shape[1]
  col = list(dados.columns)
  for k in range(0, m):
    for i in range(0, m):
      #dados['hwy'].corr(dados['displ'])
      cr = dados[col[k]].corr(dados[col[i]])
      mc.append(cr)
  
  mc = np.array(mc).reshape(m,m)
  return mc

In [112]:
dados = carros.iloc[:, [2,4,7,8]]

In [113]:
dados.head()

displ  cyl  cty  hwy
0    1.8    4   18   29
1    1.8    4   21   29
2    2.0    4   20   31
3    2.0    4   21   30
4    2.8    6   16   26

In [114]:
X = np.array(dados.iloc[:, [3]])
Y = np.array(dados.iloc[:, [0]])

In [115]:
correlacao(X, Y)

array([-0.76602])

In [116]:
m = matrizCorr(dados)

In [117]:
m

array([[ 1.        ,  0.93022702, -0.79852397, -0.76602   ],
       [ 0.93022702,  1.        , -0.80577141, -0.76191235],
       [-0.79852397, -0.80577141,  1.        ,  0.95591591],
       [-0.76602   , -0.76191235,  0.95591591,  1.        ]])

In [118]:
#Conferência com a função pronta do pandas
dados.corr()

displ       cyl       cty       hwy
displ  1.000000  0.930227 -0.798524 -0.766020
cyl    0.930227  1.000000 -0.805771 -0.761912
cty   -0.798524 -0.805771  1.000000  0.955916
hwy   -0.766020 -0.761912  0.955916  1.000000

In [119]:
m2 = matrizCorr_(dados)
m2

array([[ 1.        ,  0.9302271 , -0.79852397, -0.76602002],
       [ 0.9302271 ,  1.        , -0.80577141, -0.76191235],
       [-0.79852397, -0.80577141,  1.        ,  0.95591591],
       [-0.76602002, -0.76191235,  0.95591591,  1.        ]])

In [120]:
dados['hwy'].corr(dados['displ'])

-0.7660200208864681

In [121]:
m.shape

(4, 4)

In [122]:
m2

array([[ 1.        ,  0.9302271 , -0.79852397, -0.76602002],
       [ 0.9302271 ,  1.        , -0.80577141, -0.76191235],
       [-0.79852397, -0.80577141,  1.        ,  0.95591591],
       [-0.76602002, -0.76191235,  0.95591591,  1.        ]])

## Seção 2: **Algoritmo de seleção de atributos baseado na correlação entre variáveis**

**Dados**: Conjunto de dados com variáveis numéricas

**Alvo**: definir a variável alvo da análise

**Atributos**: demais variáveis (exceto alvo)

**Fronteira**: valor entre 0 e 1 definido com o limite de correlação para considerar elevado e eliminar o atributo

**Critério de eliminação**: critério para eliminar um dos atributos em um par que tenha correção igual ou maior que a fronteira definida


Etapas:
* Calcular matriz de correlação entre os atributos
* Comparar pares de atributos
* Para cada par de atributos, identificar e desconsiderar a correlação de um atributo com ele mesmo (correlações = 1)
* Para cada par de atributo restante buscar correlações >= fronteira
* Aplicar critério de eliminação do atributo
* Retornar atributos (sem duplicação) que foram mantidos após a aplicação das regras


In [123]:
def matrizCorr_Select(dados, fronteira):
  """
  Função cálcula matriz de correlação de um conjunto de dados
  Esta versão da função usa métodos embutidos para agilizar
  o tratamento de conjuntos de dados grandes
  """
  mc = []
  fs = []
  m = dados.shape[1]
  col = list(dados.columns)
  for k in range(0, m):
    for i in range(0, m):
      cr = dados[col[k]].corr(dados[col[i]])
      mc.append(cr)
      if abs(cr) < fronteira:
        fs.append(tuple([k,i,cr]))
  
  mc = np.array(mc).reshape(m,m)
  return mc, fs


def selectCand(candidatos):
  """
  Seleciona candidatos únicos a partir dos dados
  da função matrizCorr_Select, tendo em vista que
  aquela função seleciona pares de atributros cuja
  correlação atende ao limite definido
  """
  c = []
  for k in range(0, len(candidatos)):
    c.append(candidatos[k][0])
    c.append(candidatos[k][1])

  features = set(c)
  return features

In [124]:
L = 0.8
sel_mc, sel_ft = matrizCorr_Select(dados, L)

In [125]:
sel_mc

array([[ 1.        ,  0.9302271 , -0.79852397, -0.76602002],
       [ 0.9302271 ,  1.        , -0.80577141, -0.76191235],
       [-0.79852397, -0.80577141,  1.        ,  0.95591591],
       [-0.76602002, -0.76191235,  0.95591591,  1.        ]])

In [126]:
sel_ft

[(0, 2, -0.7985239689348552),
 (0, 3, -0.7660200208864681),
 (1, 3, -0.7619123538971945),
 (2, 0, -0.7985239689348552),
 (3, 0, -0.7660200208864681),
 (3, 1, -0.7619123538971944)]

In [127]:
selectCand(sel_ft)

{0, 1, 2, 3}

In [170]:
sel_ft

[(0, 2, -0.7985239689348552),
 (0, 3, -0.7660200208864681),
 (1, 3, -0.7619123538971945),
 (2, 0, -0.7985239689348552),
 (3, 0, -0.7660200208864681),
 (3, 1, -0.7619123538971944)]

In [171]:
min(sel_ft)

(0, 2, -0.7985239689348552)

## Seção 3: Algoritmo de força bruta para comparação de combinações de atributos

Não foi implementado o algoritmo para execução automática desta abordagem de seleção dos atributos através de força bruta, mas apresentamos a seguir um exemplo simplificado executado os passos de maneira manual a partir da combinação de atributos de um subconjunto de dados que foi usado nas seções anteriores.

In [128]:
from sklearn.metrics import accuracy_score

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
y = dados.hwy

In [131]:
X1 = dados.iloc[:, [0, 1]]
X2 = dados.iloc[:, [0]]
X3 = dados.iloc[:, [1]]

In [132]:
def featSelectEvaluate(X, y):
  #Divisão dos valores em treino e teste
  #OBSERVAÇÃO: random_state está sendo usado para reprodutibilidade dos resultados
  X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=42)
  
  dtree.fit(X_train, y_train)

  y_pred = dtree.predict(X_test)

  acc = accuracy_score(y_test, y_pred)

  return acc

In [133]:
acc1 = featSelectEvaluate(X1, y)
acc1

0.2127659574468085

In [134]:
acc2 = featSelectEvaluate(X2, y)
acc2

0.19148936170212766

In [135]:
acc3 = featSelectEvaluate(X3, y)
acc3

0.23404255319148937

In [136]:
#Nesta abordagem seria selecionada a abordagem com o maior valor da métrica
max(acc1, acc2, acc3)

0.23404255319148937

In [137]:
print(acc1, acc2, acc3)

0.2127659574468085 0.19148936170212766 0.23404255319148937


Conforme apresentado acima, nesta abordagem seria selecionada a opção $X3$ que equivaleria ao uso apenas do atributo identificado pelo índice 1 no subconjunto de dados analisado.

###MAPEAMENTO DE FEATURES. Analisar se será mantido

In [138]:
carros.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [139]:
carros2 = pd.get_dummies(data=carros,
               prefix=['class', 'fl'],
               columns=['class', 'fl'])

In [140]:
carros2.head()

manufacturer model  displ  year  cyl  ... fl_c fl_d  fl_e  fl_p  fl_r
0         audi    a4    1.8  1999    4  ...    0    0     0     1     0
1         audi    a4    1.8  1999    4  ...    0    0     0     1     0
2         audi    a4    2.0  2008    4  ...    0    0     0     1     0
3         audi    a4    2.0  2008    4  ...    0    0     0     1     0
4         audi    a4    2.8  1999    6  ...    0    0     0     1     0

[5 rows x 21 columns]

In [141]:
carros2['trans_auto'] = None

In [142]:
#Criação manual de variável dummy para transmissão 
#dividir apenas em auto=1 ou manual=0

trans_auto=[]
for k in range(0, len(carros2)):
  if 'auto' in carros2['trans'][k]:
    carros2['trans_auto'][k] = 1
  else:
    carros2['trans_auto'][k] = 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


In [143]:
carros2.head()

manufacturer model  displ  year  cyl  ... fl_d fl_e  fl_p  fl_r  trans_auto
0         audi    a4    1.8  1999    4  ...    0    0     1     0           1
1         audi    a4    1.8  1999    4  ...    0    0     1     0           0
2         audi    a4    2.0  2008    4  ...    0    0     1     0           0
3         audi    a4    2.0  2008    4  ...    0    0     1     0           1
4         audi    a4    2.8  1999    6  ...    0    0     1     0           1

[5 rows x 22 columns]

In [144]:
carros2['trans_auto'][0]

1

In [145]:
carros2.drop(columns=[
                      'manufacturer', 'model', 'year', 'trans', 'drv'
                      ],
             inplace=True)

In [146]:
carros2.head()

displ  cyl  cty  hwy  class_2seater  ...  fl_d  fl_e  fl_p  fl_r  trans_auto
0    1.8    4   18   29              0  ...     0     0     1     0           1
1    1.8    4   21   29              0  ...     0     0     1     0           0
2    2.0    4   20   31              0  ...     0     0     1     0           0
3    2.0    4   21   30              0  ...     0     0     1     0           1
4    2.8    6   16   26              0  ...     0     0     1     0           1

[5 rows x 17 columns]

In [147]:
m2 = matrizCorr(carros2)

In [148]:
m2.shape

(17, 17)

## Seção 4: Aplicação dos algoritmos em séries temporais com termos defasados

### Criação do dataset dos termos defasados

In [149]:
arquivo = 'https://raw.githubusercontent.com/janiosl/python.ds/master/data/yahoo_stock_12-12-2020.csv'
acoes = pd.read_csv(arquivo)
acoes.head()

Ticker        Date       High  ...      Close     Volume  Adj Close
0  GGBR4.SA  2010-01-04  29.799999  ...  29.600000  2827700.0  25.257845
1  GGBR4.SA  2010-01-05  30.170000  ...  30.100000  4480400.0  25.684504
2  GGBR4.SA  2010-01-06  30.379999  ...  30.299999  4499900.0  25.855158
3  GGBR4.SA  2010-01-07  30.379999  ...  29.620001  5695900.0  25.274918
4  GGBR4.SA  2010-01-08  29.879999  ...  29.540001  4269500.0  25.206648

[5 rows x 8 columns]

In [189]:
close = acoes.Close[:20]
close.head()

0    29.600000
1    30.100000
2    30.299999
3    29.620001
4    29.540001
Name: Close, dtype: float64

In [190]:
close.describe()

count    20.000000
mean     28.099000
std       1.772150
min      25.340000
25%      26.222500
50%      28.775001
75%      29.545001
max      30.299999
Name: Close, dtype: float64

In [191]:
len(close)

20

In [154]:
def ts_lags(ts, w):
  """
  Função recebe uma série temporal e retorna
  os termos defasados com base no tamanho de
  janela deslizante definido
  Parâmetros:
    ts = Série Temporal
    w = tambanho da janela deslizante
  Retorno
    legs = Dataset com termos defasados
  """
  #Divisão da série em termos defasados
  n_lags = len(ts) - w          #Quantidade de features (termos defasados)
  lags = np.zeros((n_lags, w))  #Matriz para armazenar features (termos defasados)

  #Variáveis de controle para dos 'deslizamento'
  start = 0
  end = start + w

  #Cada rodada do loop criará um termo defasado
  for k in range(0, n_lags):
  #for k in range(0, len(ts)):
    #Filtra 'w' observações e as armazenam na matriz 'legs'
    lags[k] = np.array(ts[start:end])

    #Avança um passo na série temporal para criar o próximo termo
    start += 1
    end += 1

  #Transformação em um dataframe
  lags = pd.DataFrame(lags.T,
                  columns=['T'+str(k) for k in range(0, lags.T.shape[1])])
  
  return lags

In [192]:
l = ts_lags(close, 5)
l

T0         T1         T2  ...        T12        T13        T14
0  29.600000  30.100000  30.299999  ...  27.600000  26.400000  26.049999
1  30.100000  30.299999  29.620001  ...  26.400000  26.049999  26.280001
2  30.299999  29.620001  29.540001  ...  26.049999  26.280001  25.530001
3  29.620001  29.540001  29.559999  ...  26.280001  25.530001  25.600000
4  29.540001  29.559999  29.350000  ...  25.530001  25.600000  25.340000

[5 rows x 15 columns]

### Aplicação do Cálculo da Matriz de Correlação

In [193]:
#Aplicação do cálculo da matriz de correlação nos termos defasados
matrizCorr_(l)

array([[ 1.        ,  0.2173729 , -0.20644333,  0.32547061, -0.43482354,
         0.35477957,  0.75833809,  0.20074054,  0.22066792,  0.57938515,
         0.42834703, -0.0546202 , -0.15469834,  0.49490307,  0.22492872],
       [ 0.2173729 ,  1.        ,  0.57048937,  0.59448376,  0.71804655,
         0.32436907,  0.69084689,  0.96412221,  0.63232847,  0.67151461,
         0.89127102,  0.85762717,  0.62067326,  0.57184048,  0.96671859],
       [-0.20644333,  0.57048937,  1.        ,  0.57464115,  0.46439427,
         0.63077096,  0.45728513,  0.75149041,  0.85302124,  0.64648548,
         0.71396796,  0.8817905 ,  0.98351917,  0.68691956,  0.59539159],
       [ 0.32547061,  0.59448376,  0.57464115,  1.        ,  0.03857174,
         0.19433427,  0.69681611,  0.6728286 ,  0.45736409,  0.56992063,
         0.7534369 ,  0.74849431,  0.48695136,  0.89310787,  0.44028313],
       [-0.43482354,  0.71804655,  0.46439427,  0.03857174,  1.        ,
         0.05824792,  0.04020738,  0.64708865, 

In [202]:
#Atributos Candidatos
L = 0.1
_, sf = matrizCorr_Select(l, L)

In [203]:
#Pares de atributos dentro da regra do algoritmo
sf

[(0, 11, -0.054620204294228134),
 (3, 4, 0.03857173916399009),
 (4, 3, 0.03857173916399009),
 (4, 5, 0.058247917098142206),
 (4, 6, 0.04020738337371342),
 (4, 13, -0.03919050421130269),
 (5, 4, 0.058247917098142206),
 (6, 4, 0.04020738337371343),
 (11, 0, -0.054620204294228134),
 (13, 4, -0.03919050421130269)]

In [204]:
#Atributos (lags) selecionadas para o modelo
f = selectCand(sf)
f

{0, 3, 4, 5, 6, 11, 13}

In [205]:
len(f)

7

# Referências:

https://github.com/janiosl/python.ds/blob/master/estatistica/estatistica_basica.ipynb

https://github.com/MLRG-CEFET-RJ/ml-class/blob/master/ml_ppcic_dim_reduc.ipynb